export const f1=async()=>{
    throw new Error("error prueba...")
}